#!/usr/bin/env bash
# show info about subdomains
function get_subdomain_info() {
  local domain=$1
  local subdomain=$2
  local subdomains=("www" "lb-01" "web-01" "web-02")

  if [[ -z "$subdomain" ]]; then
    for sub in "${subdomains[@]}"; do
      dig "$sub.$domain" +short | awk '{print "The subdomain '"$sub"' is a '"$(dig -t "$1" "$sub.$domain" +short)"' record and points to '"$1"'"}'
    done
  else
    dig "$subdomain.$domain" +short | awk '{print "The subdomain '"$subdomain"' is a '"$(dig -t "$1" "$subdomain.$domain" +short)"' record and points to '"$1"'"}'
  fi
}

domain=$1
subdomain=$2

get_subdomain_info "$domain" "$subdomain"

