#!/usr/bin/env bash
# install and configure nginx server


sudo apt-get update

sudo apt-get upgrade

sudo apt-get install nginx -y

sudo rm /etc/nginx/sites-available/default

sudo bash -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
            try_files \$uri
\$uri/ =404;
    }
}" > /etc/nginx/sites-available/default'

sudo bash -c 'echo "Hello World!" > ~/index.html'

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
