#!/usr/bin/env bash
# install and configure nginx server


sudo apt update

sudo apt install nginx -y

sudo echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
               	return 200
	'Hello World!';
        }
}" | sudo tee /etc/nginx/site-available/default

sudo ln -s /etc/nginx/site-available/default /etc/nginx/site-enabled/

sudo service restart nginx
