#!/usr/bin/env bash
# install and configure nginx server


sudo apt-get update

sudo apt-get upgrade

sudo apt-get install nginx -y

sudo rm /etc/nginx/sites-available/default

sudo bash -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
            return 200
	\"Hello World!\";
    }
}" > /etc/nginx/sites-available/default'


sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
