#!/usr/bin/env bash
# install and configure nginx server


sudo apt-get update

sudo apt-get upgrade

sudo apt-get install nginx -y

sudo bash -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

	location / {
		return 200
	\"Hello World\";
	}

        location /redirect_me {
            return 301
	https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location /not_found {
		return 404
	\"Ceci n'\''est pas une page\"
	}
}" > /etc/nginx/sites-available/default'

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
