#!/bin/bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i 's/http {/&\n	add_header X-Served-By $hostname;/' /etc/nginx/nginx.conf
sudo service nginx restart
