#!/usr/bin/env bash
# configure nginx web server to listen on port 80
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sudo service nginx restart
