#!/usr/bin/env bash
# corrects nginx port to listen to 80
service nginx stop

rm /etc/nginx/sites-enabled/default

echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
" > /etc/nginx/sites-enabled/default

service nginx start

service nginx status

