#!/usr/bin/env bash
#init script to manage a process

if [ "$#" -ne 1 ];
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit $?
fi
if [ "$1" != "start" ] && [ "$1" != "stop" ] && [ "$1" != "restart" ];
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit $?
fi
file=/var/run/my_process.pid
if [ "$1" == "start" ]
then
	./manage_my_process &
	echo "$!" > "$file"
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
	kill "$(cat file)"
	rm "$file"
	echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
	kill "$(cat file)"
	rm "$file"
	./manage_my_process &
	echo "$!" > "$file"
	echo "manage_my_process restarted"
fi
