#!/usr/bin/env bash
# print using while loop

var=10
while [ $var -gt 0 ];
do
	if [ $var -eq 3 ];
	then
		echo "good luck"
	elif [ $var -eq 7 ];
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
	var=$((var - 1))
done
