#!/usr/bin/env bash
#print clock

hour=1
while [ $hour -lt 13 ];
do
	echo "hour: $hour"
	min=1
	while [ $min -lt 60 ];
	do
		echo "$min"
		min=$((min + 1))
	done
	min=$min
	hour=$((hour + 1))
done
hour=$hour
