#!/usr/bin/env bash
# Fixing the apache bugs in the docker container

sed -i '/VirtualHost>/a <VirtualHost *:8080>\nServerAdmin webmaster@localhost\nDocumentRoot /var/www/html\n</VirtualHost>' /etc/apache2/sites-available/000-default.conf

sed -i '/Listen 80/a Listen 0.0.0.0:8080' /etc/apache2/ports.conf

service apache2 restart
