#!/usr/bin/env bash
# make nginx run as user nginx and set all ports to 8080
sudo service nginx stop
sudo chmod 774 /etc/nginx/nginx.conf
sudo chmod 774 /etc/nginx/sites-available/default
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
bash -u nginx nginx
sudo service nginx restart
